### PR TITLE
initial version of ebirdregionspecies

### LINKED ISSUE #85: Get species for location / region
I recently helped a fellow eBirder answer a question about the total number of species seen at hotspots within a distance of his home. This involved a couple of eBird API functions that aren't yet included in rebird:

1. [Get nearby hotspots](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#674e81c1-6a0c-4836-8a7e-6ea1fe8e6677)
2. [Get species list for a region](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#55bd1b26-6951-4a88-943a-d3a8aa1157dd)

I've got R code up and running for both of these now, and am happy to tidy it up and submit as pull requests for the package - hopefully it'll be useful for other people. 
I can see that #83 is already open for the first API call, so I'm raising this to cover the second one.

Hope this all sounds OK? Do let know if there's anything I should bear in mind, or I inadvertantly go astray with the fork > branch > pull request process!

### PR DESCRIPTION
**Pull request by dbradnum**
## Description
This introduces a new function to wrap another API endpoint, retrieving codes for all species recorded in a region or hotspot. 

Hopefully this covers most things we need, though I'd note a few small things and welcome comments:

- it's debatable whether the function should return a character vector or a single-column tibble. I ended up going for the latter, to make it really easy to join with eBird taxonomy - but don't mind switching if you have a strong preference the other way.
- I've added tests for the new functions, and these pass. As well as expected failures with ebirdfreq (as discussed in #82), I spotted a couple of other test failures that look like they're caused by underlying data changes. Happy to fix these here if that would help?
- I've not regenerated the help docs, since I'm on a later version of roxygen2 and so these would be inconsistent.
- While ticking off the API function in the list at the end of README.md, I also slightly re-ordered the checklist to reflect the latest eBird API docs.

## Related Issue
This fixes #85 

## Example
`ebirdregionspecies("GB-ENG")
ebirdregionspecies("L1796097")`

### CODE REVIEW

**Comment by sebpardo** [comment]
This is great @dbradnum! Thank you for taking the time to submit this PR.

I don't see any major issues but I noticed you couldn't use `ebird_GET()` as the function can't deal with flat JSON structures. The one problem this brings is that some errors are now uninformative. Take for example when you provide an invalid API key: 

```r
> ebirdregionspecies("GB-ENG-LND") # with valid API key
# A tibble: 304 x 1
   speciesCode
   <chr>      
 1 bahgoo     
 2 snogoo     
 3 gragoo     
 4 gwfgoo     
 5 tunbeg1    
 6 pifgoo     
 7 brant      
 8 bargoo     
 9 cangoo     
10 rebgoo1    
# … with 294 more rows
> Sys.unsetenv('EBIRD_KEY')
> Sys.setenv(EBIRD_KEY = 'a')
> ebirdregionspecies("GB-ENG-LND") 
Error: parse error: premature EOF
                                       
                     (right here) ------^
```

Part of the perks of using `ebird_GET()` is that it accounts for these potential error and provides adequate messaging:

```r
> Sys.unsetenv('EBIRD_KEY')
> Sys.setenv(EBIRD_KEY = 'a')
> ebirdregioninfo("GB-ENG-LND") # uses ebird_GET()
Error in ebirdregioninfo("GB-ENG-LND") : 
  Forbidden (HTTP 403). Failed to connect to eBird API. Invalid token.
```

I think there are three possible ways to deal with this: you can edit `ebird_GET()` so that it can also deal with single-column API output, you can create a new helper function (perhaps called `ebird_GET_single()` that specifically deals with single-column output and includes all the error checks that `ebird_GET()` has, or you could just copy the error checks straight into `ebirdregionspecies()`. I personally think the second option would be best, as it allows others to use the helper function for any future single-column API requests, and makes it easier to maintain given any changes to the API request can be done in a single file. What do you think?

I agree that keeping the output as a tibble is best for consistency with the other `rebird` functions, and to make it easy to merge with the taxonomy. No need to update the docs and tests, I need to submit a new version to CRAN soon (due to `ebirdfreq()` failing) so I'll be fixing those as well among other things.

And lastly, don't forget to add your name as an author of the function and a contributor to the package (in the DESCRIPTION file).

Thanks again!

**Comment by dbradnum** [comment]
Thanks @sebpardo  - glad it's on the right track! I meant to ask you about `ebird_GET()` but forgot, so thanks for picking this up and giving those pointers. I'll take a look and try to implement one of your first two options.

**Comment by dbradnum** [comment]
I ended up with your first option, handling the single-unnamed-column case in `ebird_GET()`.  This seemed the easiest way to retain all the existing checks, and all being well we can continue to use the same helper for future API calls. Tests on existing ones pass as before, so I think this should be safe. 

One other option that occurred to me was introducing a new parameter on `ebird_GET()`, indicating whether to convert the result into a data.frame (the default, as it did before) or into a single column (the new case). The benefit of this would be saving the performance cost of checking the JSON structure... but I think this is likely to be very cheap compared to the API call itself, so probably not a big deal.     

Let me know if you'd prefer something different, or there's anything else that needs to be added/changed.

**Comment by sebpardo** [comment]
This is great! Looks good to merge. I like they way you check for single columns in `ebird_GET()`, and I agree that performance won't be an issue here given that we are much more limited by the API than R.

**Pull request merged**
