### PR TITLE
Use vapply instead of sapply

### PR DESCRIPTION
**Pull request by ateucher**
I had used `sapply` in a couple of places - replacing with `vapply` for safety

### CODE REVIEW

**Comment by sckott** [comment]
nice!

**Comment by sebpardo** [comment]
Why is `vapply` safer than `sapply`?

**Comment by ateucher** [comment]
They both simplify the output to an atomic vector, but `sapply` guesses what the output type should be, but you tell `vapply` explicitly what it should be via `FUN.VALUE`. There's a good explanation in Hadley Wickham's book: http://adv-r.had.co.nz/Functionals.html#functionals-loop

**Comment by sebpardo** [comment]
Thank you for the explanation @ateucher!

**Comment by ateucher** [comment]
No problem! :)

**Pull request merged**
