### PR TITLE
Add support for hotspot info into `ebirdregioninfo()` function

### PR DESCRIPTION
**Pull request by sebpardo**
Based on  @gbabineau 's PR, I noticed it would be easiest to include the /ref/hotspot/info API request into the `ebirdregioninfo()` function rather than create a standalone function to do so (`ebirdhotspotinfo()`). The main thing missing from this function is proper error checking and messaging, since it does not used `ebird_GET()`.

 @gbabineau , I can give you access to my fork so you can add changes to this branch and PR.

Edit: 

### To Do list

- [x] update `ebirdregioninfo()` to include hotspot info
- [x] add proper error checking and messaging (might be easiest to just copy the error messaging code from `ebird_GET()`
- [x] write updated tests 
- [x] update documentation, README, and bump version

### CODE REVIEW

**Comment by gbabineau** [comment]
Sounds good.  I will do so. I am on business travel this week working long
hours and then heading straight to the beach and will be birding long hours
so wont get to it for a week or so.

Guy

**Comment by sebpardo** [comment]
No rush, birding comes first! (I was actually in Belize last week, birding there is great!)

I've sent you the invite so you can edit my fork, make sure you make your commits in the `hotspotinfo` branch, and once you push onto my fork they should appear automatically in this PR. I've also added a task list in the original post to give us both a rough idea what needs to be done before merging.

Have a great trip!

**Comment by sebpardo** [comment]
Hi @gbabineau , I've made a number of edits to the function and updated the documentation accordingly. The major difference is that I changed the way in which the json object is turned into a data frame so that the column classes are correct from the beginning, so we don't have to change the classes manually. Please have a look and tell me if you think before I merge this PR.

**Comment by gbabineau** [comment]
Thanks @sebpardo, this looks good! Sorry I have been busy. I am glad you figured out a way not to keep the column class info. I think the documentation (man pages, vignette) still need to be updated. I am on travel without access to my computer so could not run it but see the tests passed or update the documentation. I can also look at it this weekend when I am home.

**Pull request merged**
